In [1]:
import numpy as np

**NumPy** (Numerical Python) is a Python library used for **fast mathematical operations** on large arrays and matrices. It provides support for:

- Multi-dimensional arrays (`ndarray`)
- Mathematical functions (like mean, dot product, etc.)
- Linear algebra, Fourier transforms, and more

It’s widely used in data science, AI, and scientific computing.

# Why Use NumPy?

- **Faster computations**: Operations on NumPy arrays are much faster than Python lists.
- **Efficient memory usage**: Uses less memory and supports large datasets.
- **Vectorized operations**: Perform operations on entire arrays without loops.
- **Built-in functions**: Offers a wide range of mathematical, statistical, and linear algebra functions.
- **Interoperability**: Works well with other libraries like Pandas, Matplotlib, and SciPy.

NumPy is essential for scientific computing and is the foundation of many data and AI tools.


In [3]:
x = np.array([1,2,3,4,5]) # input array : a list is passed
print("List passed:",x)
y = np.array((1,2,3,4,5)) # here tupple is passed
print("Tuple passed:",y)

List passed: [1 2 3 4 5]
Tuple passed: [1 2 3 4 5]


To create an `ndarray`, we can pass a `list`, `tuple` or any array-like object into the array() method, and it will be converted into an `ndarray`

In [4]:
print("Type of x:", type(x))
print("Type of y:", type(y))

Type of x: <class 'numpy.ndarray'>
Type of y: <class 'numpy.ndarray'>


### 0 - D Array

A **0D array** (zero-dimensional array) in NumPy is a scalar — it contains only a single value.

In [5]:
arr = np.array(123)
print(arr)

123


# n-D Array

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print("Higher dimention array:\n", arr)

Higher dimention array:
 [[[[[1 2 3 4]]]]]


In [ ]:
print("Shape: ", arr.shape)

Shape:  (1, 1, 1, 1, 4)


# Data Types in NumPy

NumPy supports various data types (dtypes) to handle different kinds of data efficiently.

### Common NumPy Data Types and Their Characters:

- **i**: Integer
  - Example: `np.int32`, `np.int64`
- **b**: Boolean
  - Example: `np.bool`
- **u**: Unsigned Integer
  - Example: `np.uint32`, `np.uint64`
- **f**: Float
  - Example: `np.float32`, `np.float64`
- **c**: Complex Float
  - Example: `np.complex64`, `np.complex128`
- **m**: Timedelta
  - Example: `np.timedelta64`
- **M**: Datetime
  - Example: `np.datetime64`
- **O**: Object
  - Example: `np.object`
- **S**: String
  - Example: `np.str_`
- **U**: Unicode String
  - Example: `np.unicode_`
- **V**: Fixed chunk of memory for other types (Void)
  - Example: `np.void`



In [10]:
a = np.array([1, 2, 3], dtype=np.float64)
print("As float: ", a)
print("Data Type: ",a.dtype)  
a = np.array([1, 2, 3], dtype=np.str_)
print("As string: ", a)
print("Data Type: ",a.dtype)  

As float:  [1. 2. 3.]
Data Type:  float64
As string:  ['1' '2' '3']
Data Type:  <U1


# NumPy dtype Codes 

In NumPy, data types can also be represented using **shorthand notations**. These notations combine a **letter** and a **number**:

- The **letter** indicates the **data type**
- The **number** indicates the **number of bytes**

---

## 📋 Common dtype Codes:

| Code | Meaning             | Example         |
|------|---------------------|-----------------|
| `i1` | Integer (1 byte)     | `np.int8`       |
| `i2` | Integer (2 bytes)    | `np.int16`      |
| `i4` | Integer (4 bytes)    | `np.int32`      |
| `i8` | Integer (8 bytes)    | `np.int64`      |
| `u1` | Unsigned int (1 byte)| `np.uint8`     |
| `u2` | Unsigned int (2 bytes)| `np.uint16`    |
| `f4` | Float (4 bytes)      | `np.float32`    |
| `f8` | Float (8 bytes)      | `np.float64`    |
| `c8` | Complex (8 bytes)    | `np.complex64`  |
| `c16`| Complex (16 bytes)   | `np.complex128` |
| `b`  | Boolean              | `np.bool_`      |
| `U`  | Unicode string       | `np.unicode_`   |
| `S`  | Byte string          | `np.string_`    |

In [ ]:
a = np.array([1, 2, 3], dtype='i4')   # 4-byte integer (int32)
b = np.array([1.5, 2.5], dtype='f8')  # 8-byte float (float64)

print(a.dtype)  
print(b.dtype)  

int32
float64


### Shallow Copy (`view()`)
- Shares **data** with the original array.
- Changes in data affect both arrays.

In [12]:
a = np.array([1, 2, 3])
b = a.view()
b[0] = 100
print("a: ", a) 

a:  [100   2   3]


### Deep Copy (copy())
- Independent copy of data.
- Changes do not affect the original.

In [13]:
c = np.array([1, 2, 3])
d = c.copy()
d[0] = 100
print("c :",c) 

c : [1 2 3]


#### Search Functions in NumPy

NumPy provides several useful functions for searching and manipulating arrays:

##### `np.searchsorted()`

The `np.searchsorted()` function returns the indices where elements should be inserted to maintain order in a sorted array.

**Syntax**: <br>
`numpy.searchsorted(a, v, side='left', sorter=None)`
- **`a`**: The sorted input array.
- **`v`**: The value or array of values to insert.
- **`side`**: ('left' or 'right') which side of the index to consider.
- **`sorter`**: Optional, an array of indices that sort a.


#### `np.where()`

The `np.where()` function is used for conditional selection and finding elements within an array.<br>It can either return indices or replace elements based on a condition.

 **Syntax**: <br>
`numpy.where(condition, [x, y])`


In [14]:
a = np.array((1,2,4,5,7,4,6,7,3,4,6,9,0,2))
x = np.where(a == 4)
print(x)

(array([2, 5, 9]),)


####  Sorting Arrays in NumPy
NumPy provides the `np.sort()` function to sort array elements. It sorts along a specified axis without modifying the original array.<br><br>
**Syntax**:<br>
`numpy.sort(a, axis=-1, kind='algorithm')`


In [23]:
arr = np.array([[3, 1, 5, 2],[6, 0, 2, 3]])
sorted_arr = np.sort(arr, axis = 0)
print('Sort about Axis 0\n',sorted_arr)

sorted_arr = np.sort(arr, axis = 1) # default
print('Sort about Axis 1\n',sorted_arr)

Sort about Axis 0
 [[3 0 2 2]
 [6 1 5 3]]
Sort about Axis 1
 [[1 2 3 5]
 [0 2 3 6]]


- `np.sort()` does not sort in-place. Use `arr.sort()` if you want to modify the original array.
- Use [::-1] to reverse the result for descending order.
- For argsort (get indices of sorted array), use `np.argsort().`