# 1D Array in NumPy

A **1D array** (one-dimensional array) is like a list of elements — a single row or line of data.


In [1]:
import numpy as np

In [ ]:
x = np.array([1,2,3,4,5,6,7]) # input array : a list is passed
print("1D Numpy array: ", x)
print("Number of dimensions: ", x.ndim)
print("Data type: ", x.dtype)
# print("Type: ", type(x))

# print("Size: ", x.size)

# print("Number of elements: ", x.itemsize)
# print("Memory size: ", x.nbytes)

1D Numpy array:  [1 2 3 4 5]
Number of dimensions:  1


Indexing

In [3]:
print("x[3]: ", x[3])
print("x[-1]: ", x[-1]) # Access the last element

x[3]:  4
x[-1]:  5


**Slicing arrays:**<br>
Slicing in python means taking elements from one given index to another given index.

In [4]:
print("x[1:5]: ", x[1:5]) # Slice elements from index 1 to index 5
print("x[-3:-1]:", x[-3:-1]) # Slice from the index 3 from the end to index 1 from the end
print("x[1:5:2]:", x[1:5:2]) # Return every other element from index 1 to index 5:

x[1:5]:  [2 3 4 5]
x[-3:-1]: [3 4]
x[1:5:2]: [2 4]


In [5]:
a = np.array([10, 20, 30], dtype=np.float32)
print(a)
print("Dimensions:", a.ndim)
print("Data Type:", a.dtype)

[10. 20. 30.]
Dimensions: 1
Data Type: float32


In [6]:
arr = np.array(['a', '2', '3'], dtype='i') # will raise error

ValueError: invalid literal for int() with base 10: 'a'

The best way to change the data type of an existing array, is to make a copy of the array with the `astype()` method.

In [9]:
arr = np.array(["1", "2", "3"])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


**Shape of an Array**<br>
The shape of an array is the number of elements in each dimension.

In [10]:
print("Shape: ", x.shape)

Shape:  (5,)


2D to 1D Array

In [16]:
# 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
# Convert to 1D
b = a.flatten()
print("Original 2D array:")
print(a)

print("\nConverted 1D array:")
print(b)

Original 2D array:
[[1 2 3]
 [4 5 6]]

Converted 1D array:
[1 2 3 4 5 6]


#### Concatenating Arrays in NumPy

In NumPy, you can concatenate arrays using the `np.concatenate()` function. This function allows you to join two or more arrays along a specified axis.

In [ ]:
# 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate along axis 0 (default for 1D arrays)
c = np.concatenate((a, b))

print("Concatenated 1D array:")
print(c)

#### Other Concatenation Functions in NumPy

Besides `np.concatenate()`, NumPy provides several other functions that allow you to concatenate arrays in different ways.

#### 1. **`np.stack()`**

- **Purpose**: Adds a new axis (dimension) to the arrays while concatenating them along that axis.
- **Usage**: `np.stack(arrays, axis=0)`
- **Note**: Unlike `concatenate()`, `stack()` increases the dimensionality of the resulting array.



In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

# Stack along a new axis (default is axis=0)
c = np.stack((a, b))

print("Stacked array:")
print(c)

Stacked array:
[[1 2]
 [3 4]]


#### 2. **`np.hstack()`**
- **Purpose**: Concatenates arrays horizontally (along axis 1). It's equivalent to `np.concatenate(..., axis=1)`.
- **Usage**: `np.hstack(arrays)`

In [18]:
# 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Horizontally stack the arrays
c = np.hstack((a, b))

print("Horizontally stacked array:")
print(c)


Horizontally stacked array:
[[1 2 5 6]
 [3 4 7 8]]


#### 3. **`np.vstack()`**
- **Purpose**: Concatenates arrays vertically (along axis 0). It's equivalent to `np.concatenate(..., axis=0)`.
- **Usage**: `np.vstack(arrays)`

In [19]:
# 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertically stack the arrays
c = np.vstack((a, b))

print("Vertically stacked array:")
print(c)


Vertically stacked array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### 4. **`np.dstack()`**
- **Purpose**: Concatenates arrays along the third axis (depth), effectively stacking them as if they were along the "z" axis.
- **Usage**: `np.dstack(arrays)`

In [20]:
# 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stack along the third axis (depth)
c = np.dstack((a, b))

print("Stacked along depth axis (3D array):")
print(c)


Stacked along depth axis (3D array):
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


#### Array Splitting in NumPy

NumPy provides several functions to split arrays:

- `np.split()`: Split array into a list of sub-arrays.
- `np.array_split()`: Similar to `np.split()`, but allows for unequal sub-arrays.
- `np.hsplit()`: Split array horizontally (column-wise).
- `np.vsplit()`: Split array vertically (row-wise).

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Split into 3 sub-arrays
new_arr = np.array_split(arr, 3)
print(new_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([10, 15, 20, 25, 30])
result = np.where(arr > 20, arr, 0) # Replace elements: keep only elements greater than 20
print(result)

[ 0  0  0 25 30]


In [24]:
arr = np.array([3, 1, 5, 2])
sort_arr = np.sort(arr)
print(sort_arr)

[1 2 3 5]
