In [ ]:
from numpy import random as rd
import numpy as np

In [4]:
x = rd.randint(100) # random integer between 0 and 100
print(x)

59


In [6]:
x = rd.rand() # random number between 0 and 1
print(x)

0.6936016456587981


In [7]:
x = rd.randint(5,45,size=(7)) # 7 random numbers between 5 and 45
print(x)

[35  5 32 11 18  9 21]


In [9]:
x = rd.randint(5,45,size=(5,6)) # 7 random numbers between 5 and 45
print(x)

[[44 39 36 32 30 38]
 [ 7 40 19 24 44  5]
 [31 16 20 19  8 20]
 [16 38 33 29 29  5]
 [19 14 21 30 14 41]]


In [ ]:
x = rd.rand(5) # 1-D array containing 5 random floats
print(x)

[0.1469971  0.26242217 0.88724412 0.35845195 0.92000311]


In [ ]:
x = rd.rand(4,5) # 2-D array of size 4 x 5
print(x)

[[0.39260229 0.5143716  0.74028465 0.49920074 0.50131706]
 [0.40735965 0.1647198  0.89819488 0.47688417 0.27499972]
 [0.31116475 0.32431668 0.90563884 0.85517444 0.91318661]
 [0.90700472 0.02249992 0.72210724 0.92966571 0.32420978]]


In [ ]:
x = rd.choice([13, 53, 37, 96]) # random choice from list
print(x)

53


In [13]:
x = rd.choice([13, 53, 37, 96], size=(3,5)) # 2-D array that consists of the values in the array parameter
print(x)

[[96 96 96 96 37]
 [13 37 37 37 37]
 [13 53 96 96 96]]


## Random Distribution
A random distribution is a set of random numbers that follow a certain probability density function.<br>

- **`Probability Density Function`**: A function that describes a `continuous probability`. i.e. probability of all values in an array.<br>

**We can generate random numbers with specific chances using the `choice()` function from NumPy's random module.**<br>
This function lets us define how likely each value is to be picked.<br>
The probabilities are set using numbers between 0 and 1:
- `0` means the value will **never** be chosen.
- `1` means the value will **always** be chosen.




In [ ]:
x = rd.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=100)
# The probability for the value to be 3 is set to be 0.1, 5 is set to be 0.3, 7 is set to be 0.6, 9 is set to be 0
# The sum of all probability numbers should be 1. else ERROR will be shown
print(x)
print("Count of 3 =", np.count_nonzero(x == 3))
print("Count of 5 =", np.count_nonzero(x == 5))
print("Count of 7 =", np.count_nonzero(x == 7))
print("Count of 9 =", np.count_nonzero(x == 9))

[7 3 5 3 5 7 7 5 3 5 7 5 7 7 7 5 5 7 7 3 3 7 7 7 5 7 7 7 7 5 7 7 7 7 7 7 5
 3 5 7 7 7 5 5 7 7 7 7 7 7 7 7 7 3 7 5 7 7 3 3 7 5 5 5 5 5 7 7 7 7 7 7 3 7
 7 7 7 5 7 5 7 7 5 7 7 7 3 7 7 7 7 7 7 7 3 7 7 3 7 7]
Count of 3 = 13
Count of 5 = 22
Count of 7 = 65
Count of 9 = 0


## Permutation
A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
rd.shuffle(arr) # The shuffle() method makes changes to the original array.
print(arr)

[3 1 5 2 4]


In [26]:
arr = np.array([1, 2, 3, 4, 5])
print(rd.permutation(arr)) # The permutation() method returns a re-arranged array (and leaves the original array un-changed).

[1 5 3 2 4]


In [29]:
from itertools import permutations
arr = np.array(['a','b','c'])
perm_tuples = list(permutations(arr))
print(perm_tuples)

[('a', 'b', 'c'), ('a', 'c', 'b'), ('b', 'a', 'c'), ('b', 'c', 'a'), ('c', 'a', 'b'), ('c', 'b', 'a')]
