# 2D Array in NumPy

A **2D array** (two-dimensional array) is like a matrix — it has rows and columns.


In [1]:
import numpy as np

In [ ]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Numpy array: \n", x)
print("Number of dimensions: ", x.ndim)
print("Data type: ", x.dtype)

Numpy array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Number of dimensions:  2


Indexing

In [8]:
print("x[1, 0]:", x[1, 0])
print("x[-1, 1]:", x[-1, 1]) # Access the 2nd element of the last sublist

x[1, 0]: 6
x[-1, 1]: 7


**Slicing arrays:**<br>
Slicing in python means taking elements from one given index to another given index.

In [9]:
print("x[1, 1:4]:", x[1, 1:4]) # From the second subarray, slice elements from index 1 to index 4
print("x[0:2, 2]:", x[0:2, 2]) # From the second element, slice elements from index 1 to index 4

x[1, 1:4]: [7 8 9]
x[0:2, 2]: [3 8]


In [11]:
b = np.array([[1, 2], [3, 4]], dtype=np.unicode_)
print(b)
print("Dimensions:", b.ndim)
print("Data Type:", b.dtype)

[['1' '2']
 ['3' '4']]
Dimensions: 2
Data Type: <U1


**Shape of an Array**<br>
The shape of an array is the number of elements in each dimension.

In [12]:
print("Shape: ", x.shape)

Shape:  (2, 5)


#### Converting 1D to 2D Array in NumPy
In NumPy, you can easily convert a **1D array** to a **2D array** by reshaping the array using the `.reshape()` method.

In [13]:
# 1D array
a = np.array([1, 2, 3, 4, 5, 6])
# Convert to 2D array (1 row and 6 columns)
b = a.reshape(2, 3)
print("Original 1D array:")
print(a)

print("\nConverted 2D array:")
print(b)

Original 1D array:
[1 2 3 4 5 6]

Converted 2D array:
[[1 2 3]
 [4 5 6]]


#### Concatenating Arrays in NumPy

In NumPy, you can concatenate arrays using the `np.concatenate()` function. This function allows you to join two or more arrays along a specified axis.

In [ ]:
# 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
c = np.concatenate((a, b), axis=0)

print("Concatenated 2D array along axis 0 (rows):")
print(c)

Concatenated 2D array along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
# Concatenate along axis 1 (columns)
c = np.concatenate((a, b), axis=1)

print("Concatenated 2D array along axis 1 (columns):")
print(c)


Concatenated 2D array along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]


In [16]:
arr = np.array([[5, 10], [15, 20]])
indices = np.where(arr > 10)
print(indices)  

(array([1, 1]), array([0, 1]))


In [17]:
arr = np.array([[5, 10], [15, 20]])
result = np.where(arr > 10, arr, -1) # Replace values less than 10 with -1
print(result)

[[-1 -1]
 [15 20]]


In [19]:
arr = np.array([[3, 7, 1], [2, 9, 5]])
# Sort along each row (axis=1)
sorted_row = np.sort(arr, axis=1)
print('sorted row wise\n', sorted_row)
# Sort along each column (axis=0)
sorted_col = np.sort(arr, axis=0)
print('sorted column wise\n', sorted_col)

sorted row wise
 [[1 3 7]
 [2 5 9]]
sorted column wise
 [[2 7 1]
 [3 9 5]]
