# 3D Array in NumPy

A **3D array** (three-dimensional array) is like a collection of 2D matrices — often called a "cube" of data.


In [1]:
import numpy as np

In [ ]:
x = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("3D Numpy array: \n", x)
print("Number of dimensions: ", x.ndim)
print("Data type: ", x.dtype)

3D Numpy array: 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Number of dimensions:  3


Indexing

In [5]:
print("x[0, 1, 2]:",x[0, 1, 2])
print("x[0, 1]:",x[0, 1])
print("x[-2, 0, -1]:", x[-2, 0, -1])

x[0, 1, 2]: 6
x[0, 1]: [4 5 6]
x[-2, 0, -1]: 3


In [6]:
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
], dtype=np.complex64)
print(c)
print("Dimensions:", c.ndim)
print("Data Type:", c.dtype)


[[[1.+0.j 2.+0.j]
  [3.+0.j 4.+0.j]]

 [[5.+0.j 6.+0.j]
  [7.+0.j 8.+0.j]]]
Dimensions: 3
Data Type: complex64


**Shape of an Array**<br>
The shape of an array is the number of elements in each dimension.

In [7]:
print("Shape: ", x.shape)

Shape:  (2, 2, 3)


#### Converting 1D to 3D Array in NumPy

In NumPy, you can convert a **1D array** to a **3D array** by reshaping the array using the `.reshape()` method.


In [9]:
# 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Convert to 3D array (1 block, 3 rows, and 3 columns)
b = a.reshape(2, 2, 3)

print("Original 1D array:")
print(a)

print("\nConverted 3D array:")
print(b)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Converted 3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Converting 2D to 3D Array in NumPy

In NumPy, you can convert a **2D array** to a **3D array** by reshaping the array using the `.reshape()` method.

In [11]:
# 2D array
a = np.array([[1, 2, 3, 4, 5, 6], [4, 5, 6, 7, 8 , 9]])

# Convert to 3D array (1 block, 2 rows, and 3 columns)
b = a.reshape(2, 2, 3)

print("Original 2D array:")
print(a)

print("\nConverted 3D array:")
print(b)

Original 2D array:
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]

Converted 3D array:
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [14]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
result = np.where((arr > 6) | (arr < 3 ), arr, 0)
print(result)

[[[1 2]
  [0 0]]

 [[0 0]
  [7 8]]]


In [17]:
arr = np.array([[[9, 1, 5], [6, 3, 7]],
                [[4, 8, 7], [7, 2, 0]]])

# Sort along last axis (axis = -1)
sorted_col = np.sort(arr, axis=-1)
print('sorted colum wise\n', sorted_col)

# Sort along axis = 1
sorted_row = np.sort(arr, axis=1)
print('sorted row wise\n', sorted_row)

# Sort along axis = 0
sorted_depth = np.sort(arr, axis=0)
print('sorted depth wise\n', sorted_depth)


sorted colum wise
 [[[1 5 9]
  [3 6 7]]

 [[4 7 8]
  [0 2 7]]]
sorted row wise
 [[[6 1 5]
  [9 3 7]]

 [[4 2 0]
  [7 8 7]]]
sorted depth wise
 [[[4 1 5]
  [6 2 0]]

 [[9 8 7]
  [7 3 7]]]
